# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseConverter.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(343, 197)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.submitButton = QtWidgets.QPushButton(self.centralwidget)
        self.submitButton.setGeometry(QtCore.QRect(250, 120, 51, 20))
        self.submitButton.setObjectName("submitButton")
        self.originLabel = QtWidgets.QLabel(self.centralwidget)
        self.originLabel.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(14)
        self.originLabel.setFont(font)
        self.originLabel.setObjectName("originLabel")
        self.targetLabel = QtWidgets.QLabel(self.centralwidget)
        self.targetLabel.setGeometry(QtCore.QRect(10, 120, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(14)
        self.targetLabel.setFont(font)
        self.targetLabel.setObjectName("targetLabel")
        self.originSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.originSpinBox.setGeometry(QtCore.QRect(100, 50, 41, 21))
        self.originSpinBox.setObjectName("originSpinBox")
        self.targetSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.targetSpinBox.setGeometry(QtCore.QRect(260, 50, 41, 21))
        self.targetSpinBox.setObjectName("targetSpinBox")
        self.baseLabel = QtWidgets.QLabel(self.centralwidget)
        self.baseLabel.setGeometry(QtCore.QRect(10, 50, 41, 16))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(14)
        self.baseLabel.setFont(font)
        self.baseLabel.setObjectName("baseLabel")
        self.toLabel = QtWidgets.QLabel(self.centralwidget)
        self.toLabel.setGeometry(QtCore.QRect(190, 50, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Menlo")
        font.setPointSize(14)
        self.toLabel.setFont(font)
        self.toLabel.setObjectName("toLabel")
        self.originLine = QtWidgets.QLineEdit(self.centralwidget)
        self.originLine.setGeometry(QtCore.QRect(80, 10, 131, 21))
        self.originLine.setObjectName("originLine")
        self.targetLine = QtWidgets.QLineEdit(self.centralwidget)
        self.targetLine.setGeometry(QtCore.QRect(80, 120, 131, 21))
        self.targetLine.setObjectName("targetLine")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.submitButton.setText(_translate("MainWindow", "Submit"))
        self.originLabel.setText(_translate("MainWindow", "Origin:"))
        self.targetLabel.setText(_translate("MainWindow", "Target:"))
        self.baseLabel.setText(_translate("MainWindow", "Base:"))
        self.toLabel.setText(_translate("MainWindow", "to"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
